### ISSUE TITLE
Prefixes and Suffixes

### ISSUE THREAD

**Issue by ProfessorProspector** [OpenModLoader/pomf#6]
This is pretty urgent, right now it's a horrid mess and it's going to get out of control. I believe POMF under Fabric was previously omitting the I. Is this still the case? Because many newly mapped classes have been using the I.

**Comment by thiakil** [comment]
I'm in favour of I prefixed

**Comment by ProfessorProspector** [comment]
We also need to decide on whether to prefix or suffix class names with the type, for example: BlockChest vs. ChestBlock; FeatureMineshaft vs. MineshaftFeature

Personally I vote for suffixes.

**Comment by TheCodedOne** [comment]
I don't think ChestBlock would go well so i vote prefixes

**Comment by TheCodedOne** [comment]
and as for I vs no I, i'd say with I
